name: build-firewall-ghcr
run-name: Build the simple firewall Docker image (using the GitHub Container Registry)

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Athens"
      - name: Get date
        id: date
        run: echo "push_date=$(date '+%H:%M@%d/%m/%Y')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Base image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/gunet/simple-firewall:latest
          labels: gr.gunet.simplefirewall.pushdate=${{ env.push_date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max